### ISSUE TITLE
Notificare 2.7.1 and up breaks my app:lintRelease task

### ISSUE THREAD

**Issue by evertsmits** [Notificare/notificare-sdk-android#1]
Hi,

When I update the notificare dependency from version 2.7.0 to 2.7.1 (and up) it breaks the task app:lintRelease with the following message:

**_Lint found 1 error and 12 warnings. First failure:
mypath/app/src/main/AndroidManifest.xml:11: Error: Class referenced in the manifest, mypath.MainActivity, was not found in the project or the libraries [MissingClass]
        <activity android:name="mypath.MainActivity"
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Lint found errors in the project; aborting build._**

Is this a known issue? Any ideas on how to resolve this issue? Or what could cause this. 
For reference I am also using the hms libs.

Overview of dependency definitions:
    **_const val notificareCore = "re.notifica:notificare-core:${Versions.notificareCore}"
    const val notificareCoreHms = "re.notifica:notificare-core-hms:${Versions.notificareCore}"
    const val notificareLocation = "re.notifica:notificare-location:${Versions.notificareLocation}"
    const val notificareLocationHms = "re.notifica:notificare-location-hms:${Versions.notificareLocation}"_**

I am sorry but I cannot really provide much code as this is a client project.

**Comment by hpinhal** [comment]
Hi @evertsmits, 

This repository contains the v3 generation of our libraries.
Support for prior versions must go through the support channel: support@notifica.re

**Comment by evertsmits** [comment]
Alright thanks, will do
