### ISSUE TITLE
Application label is sent on headers, but contains non-accepted chars.

### ISSUE THREAD

**Issue by jrtapiaO** [Notificare/notificare-sdk-android#21]
Application label is sent on headers, but contains non-accepted chars. As the client of the app is in Brazil, the name of the app has to have the **í** character which is not accepted in OkHttp. hence Notificare cannot be initialised.
Suggestion: before adding the application label (app name) on the request headers, check and replace unsupported chars.
The code that checks values in OkHttp is:
```
class Headers { 
...
  private fun checkValue(value: String, name: String) {

        for (i in value.indices) {

          val c = value[i]

          require(c == '\t' || c in '\u0020'..'\u007e') {

            format("Unexpected char %#04x at %d in %s value", c.toInt(), i, name) +

                (if (isSensitiveHeader(name)) "" else ": $value")

          }
        }
      }
...
}
```

**Comment by hpinhal** [comment]
Hi @jrtapiaO.

Thanks for reporting this issue and for the investigation beforehand. 
The PR linked above fixes this issue. It will be released today in the schedule 3.2.0 update.
