### ISSUE TITLE
Notification not received for huawei device that uses only hms

### ISSUE THREAD

**Issue by gtsak1** [Notificare/notificare-sdk-android#48]
Notification is sent and received successfully by non-huawei devices as well as by huawei devices using both gms+hms. Problem is that newest huawei devices running only hms seem to not allow app to send remote notification (see attached screenshots). Also, hms only devices have transport protocol set to "Notificare", not "HMS". I am not sure if that is the problem. Notificare version used is 3.3.1

![Screenshot 2022-10-18 at 11-29-37 Notificare - Marketing Automation Platform](https://user-images.githubusercontent.com/58042128/196398927-564cf6f4-5896-4788-9f81-069d8344e094.png)
![Screenshot 2022-10-18 at 10-32-25 Notificare - Marketing Automation Platform](https://user-images.githubusercontent.com/58042128/196398990-06c0cdd9-931b-4e4b-b037-9a8b3e30ac07.png)
![Screenshot 2022-10-18 at 10-32-48 Notificare - Marketing Automation Platform](https://user-images.githubusercontent.com/58042128/196399018-b8968db4-138c-4bc1-9a87-0decd3e72302.png)

**Comment by hpinhal** [comment]
Hi @gtsak1 ,

You must include the  `push-hms` peer dependency for supporting HMS devices. 

```
implementation "re.notifica:notificare-push:$notificare_version"
implementation "re.notifica:notificare-push-gms:$notificare_version"        // Enable support for Google Mobile Services.
implementation "re.notifica:notificare-push-hms:$notificare_version"
```

I've quickly tested it with our sample app and push messages are being received.

We intend to keep the GitHub issues as a channel for reporting bugs.
For support-related matters, please create a ticket via our [helpdesk](https://notificare.zendesk.com/agent/) or send an email to support@notifica.re. That way we can provide more contextualised support.

**Comment by hpinhal** [comment]
We cannot reproduce this with our HMS-only devices.

Can you share some evidence of the problem? Application logs from the configuration phase until after you've enabled remote notifications, a sample app where the problem occurs.

For the logs, enable debug logging by adding the following to your `AndroidManifest.xml` application node:

```
<meta-data android:name="re.notifica.debug_logging_enabled" android:value="true" />
```

**Comment by gtsak1** [comment]
It seems there is certificate fingerprint error, although I have configured SHA-256 certificate fingerprint in developer Huawei appGallery Connect

E/Notificare: [ServiceManager] Failed to retrieve HMS token.
    com.huawei.hms.common.ApiException: 6003: certificate fingerprint error

**Comment by hpinhal** [comment]
Unlike Firebase, Huawei requires you to configure all fingerprints — not just the release fingerprint.
I suggest checking your signing configurations (debug & release), configuring those in the Huawei portal and downloading their configuration file. From that error, we can be sure it's a configuration mismatch. 

Regarding the warning, the SDK only prints the warning but does not restrict anything. We must, indeed, improve that warning since it's only checking for the FCM permission, which is not applicable in this case. I will create a task for correctly checking and issuing the appropriate warning, but you can discard this warning.

**Comment by gtsak1** [comment]
Problem solved by adding apps in the Huawei portal for every product flavor of the project and by adding debug and release SHA-256 certificate fingerprints for each app in the Huawei portal.
